# Generated by Django 5.1 on 2026-05-28 07:37

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql="CREATE EXTENSION IF NOT EXISTS vector;", reverse_sql="DROP EXTENSION IF EXISTS vector;"),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(db_index=True, max_length=50)),
                ('chapter', models.IntegerField(db_index=True)),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
            ],
            options={
                'ordering': ['book', 'chapter', 'verse'],
                'indexes': [pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='bible_embedding_idx', opclasses=['vector_cosine_ops'])],
                'unique_together': {('book', 'chapter', 'verse')},
            },
        ),
    ]
