# Generated by Django 5.1 on 2026-05-28 13:37

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bibleverse',
            name='bible_embedding_idx',
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='bible_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
