# Generated by Django 5.1 on 2026-05-29 05:07

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_bibleverse_bible_embedding_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bibleverse',
            name='bible_embedding_hnsw_idx',
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='bible_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
